# Generated by Django 4.2.4 on 2023-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_csv', models.FileField(upload_to='uploads/')),
                ('processed_csv', models.FileField(upload_to='processed/')),
            ],
        ),
    ]
